import { Projects } from "../modals/Projects";
import { Plots } from "../modals/Projects/Plots";
import { ObservationSessions, ObservationTypes } from "../modals/Projects/Observations";
import { sortLayout } from "./observationSort";

export type Stats={average:number|null;minimum:number|null;maximum:number|null;count:number};
export type RawObservationRow={date:Date;round:number;session:string;plotId:string;plot:string;treatmentId:string;treatment:string;replicationId:string;replication:string;observation:string;value:unknown;unit:string;note:string;observationTypeId:string;measurementSessionId:string};
export type SessionAnalysis={id:string;label:string;capturedAt:Date;round:number;comparePlots:Array<{plotId:string;plot:string;treatmentId:string;replicationId:string;value:number}>;compareTreatments:Array<{treatmentId:string;treatment:string}&Stats>};
export type ObservationAnalysis={type:any;records:any[];summary:Stats&{byTreatment:Array<{treatmentId:string;treatment:string}&Stats>};sessions:SessionAnalysis[];treatmentSeries:Array<{treatmentId:string;treatment:string;values:Array<{sessionId:string;session:string;capturedAt:Date;value:number|null;count:number}>}>;timeSeries:Array<{plotId:string;plot:string;treatmentId:string;replicationId:string;replication:string;values:Array<{sessionId:string;session:string;capturedAt:Date;value:number}>}>};
export type ProjectObservationSnapshot={project:any;plots:any[];types:any[];rawRows:RawObservationRow[];analyses:ObservationAnalysis[]};
export const calculateStats=(values:number[]):Stats=>({average:values.length?values.reduce((a,b)=>a+b,0)/values.length:null,minimum:values.length?Math.min(...values):null,maximum:values.length?Math.max(...values):null,count:values.length});
const dayLabel=(date:Date)=>date.toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"});
const timeLabel=(date:Date)=>date.toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit",timeZone:"UTC"});

export async function buildProjectObservationSnapshot(projectId:string,userId:string,onlyTypeId?:string):Promise<ProjectObservationSnapshot|null>{
  const project=await Projects.findOne({_id:projectId,userId}).lean();if(!project)return null;
  const typeQuery:any={projectId};if(onlyTypeId)typeQuery._id=onlyTypeId;
  // A snapshot uses exactly four queries: authorization/project, then types,
  // sessions-with-records, and the project layout in parallel.
  const [types,sessions,plots]=await Promise.all([ObservationTypes.find(typeQuery).sort({name:1}).lean(),ObservationSessions.find({projectId,...(onlyTypeId?{observationTypeId:onlyTypeId}:{})}).sort({capturedAt:1,_id:1}).lean(),Plots.find({projectId,userId}).sort({treatment:1,replication:1,title:1}).lean()]);if(onlyTypeId&&!types.length)return null;
  const pm=new Map(plots.map((p:any)=>[p._id.toString(),p])),tm=new Map(types.map((t:any)=>[t._id.toString(),t])),sessionsByType=new Map<string,any[]>(),labels=new Map<string,string>(),rounds=new Map<string,number>();
  sessions.forEach((s:any)=>{const key=s.observationTypeId.toString();sessionsByType.set(key,[...(sessionsByType.get(key)||[]),s])});
  sessionsByType.forEach(typeSessions=>{const dayRounds=new Map<string,number>();typeSessions.forEach((s:any)=>{const date=new Date(s.capturedAt),day=date.toISOString().slice(0,10),round=(dayRounds.get(day)||0)+1;dayRounds.set(day,round);labels.set(s._id.toString(),`${dayLabel(date)} · ${timeLabel(date)} · Round ${round}`);rounds.set(s._id.toString(),round)})});
  // Plot relationships come only from the single preloaded plot map. Custom plot
  // names are never parsed. Orphaned values stay stored but are omitted here.
  const rawRows=sortLayout(sessions.flatMap((s:any):RawObservationRow[]=>s.records.flatMap((r:any):RawObservationRow[]=>{const p:any=pm.get(r.plotId?.toString());if(!p)return[];const tid=s.observationTypeId.toString(),t:any=tm.get(tid),sid=s._id.toString(),treatmentId=String(p.treatment),replicationId=String(p.replication);return[{date:new Date(s.capturedAt),round:rounds.get(sid)||s.sequence||0,session:labels.get(sid)||`Round ${s.sequence}`,plotId:p._id.toString(),plot:p.title,treatmentId,treatment:`T${p.treatment}`,replicationId,replication:`R${p.replication}`,observation:t?.name||"",value:r.value,unit:t?.unit||"",note:r.note||"",observationTypeId:tid,measurementSessionId:sid}]})),"replication");
  const analyses=types.filter((t:any)=>t.dataType==="number").map((type:any):ObservationAnalysis=>{const tid=type._id.toString(),rows=rawRows.filter(r=>r.observationTypeId===tid),typeRecords=(sessionsByType.get(tid)||[]).flatMap((s:any)=>s.records),plotSeries=new Map<string,any>();
    const sessionAnalyses=(sessionsByType.get(tid)||[]).map((session:any,index:number):SessionAnalysis=>{const sid=session._id.toString(),sessionRows=rows.filter(r=>r.measurementSessionId===sid),groups=new Map<string,number[]>();const comparePlots=sortLayout(sessionRows,"replication").map(r=>{const n=Number(r.value);if(Number.isFinite(n))groups.set(r.treatmentId,[...(groups.get(r.treatmentId)||[]),n]);const series=plotSeries.get(r.plotId)||{plotId:r.plotId,plot:r.plot,treatmentId:r.treatmentId,replicationId:r.replicationId,replication:r.replication,values:[]};if(Number.isFinite(n))series.values.push({sessionId:sid,session:labels.get(sid)||`Round ${index+1}`,capturedAt:new Date(session.capturedAt),value:n});plotSeries.set(r.plotId,series);return{plotId:r.plotId,plot:r.plot,treatmentId:r.treatmentId,replicationId:r.replicationId,value:n}});return{id:sid,label:labels.get(sid)||`Round ${index+1}`,capturedAt:new Date(session.capturedAt),round:rounds.get(sid)||index+1,comparePlots,compareTreatments:[...groups].sort(([a],[b])=>Number(a)-Number(b)).map(([treatmentId,v])=>({treatmentId,treatment:`T${treatmentId}`,...calculateStats(v)}))}});
    const treatmentIds=[...new Set(rows.map(r=>r.treatmentId))].sort((a,b)=>Number(a)-Number(b));const treatmentSeries=treatmentIds.map(treatmentId=>({treatmentId,treatment:`T${treatmentId}`,values:sessionAnalyses.map(s=>{const match=s.compareTreatments.find(x=>x.treatmentId===treatmentId);return{sessionId:s.id,session:s.label,capturedAt:s.capturedAt,value:match?.average??null,count:match?.count??0}})}));const allGroups=new Map<string,number[]>();rows.forEach(r=>{const n=Number(r.value);if(Number.isFinite(n))allGroups.set(r.treatmentId,[...(allGroups.get(r.treatmentId)||[]),n])});return{type,records:typeRecords,summary:{...calculateStats(rows.map(r=>Number(r.value)).filter(Number.isFinite)),byTreatment:[...allGroups].map(([treatmentId,v])=>({treatmentId,treatment:`T${treatmentId}`,...calculateStats(v)}))},sessions:sessionAnalyses,treatmentSeries,timeSeries:[...plotSeries.values()]};});
  return{project,plots,types,rawRows,analyses};
}
