import { ObservationAnalysis, SessionAnalysis } from "./observationAnalysis";
import { ComparisonResult } from "./observationComparison";
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]!));
export type ChartKind="plots"|"time"|"treatments";
const colors=["#2fbfa9","#3978c5","#e29b3f","#9b62c7","#d35f78","#58756f"];
export function observationChartSvg(analysis:ObservationAnalysis,kind:ChartKind,width=720,height=360,selected?:SessionAnalysis){
  const session=selected||analysis.sessions.at(-1);const unit=analysis.type.unit?` (${analysis.type.unit})`:"";const suffix=kind==="time"?"":session?` - ${session.label}`:"";const title=kind==="plots"?`Plot Comparison${suffix}${unit}`:kind==="time"?`Growth Over Time${unit}`:`Treatment Comparison${suffix}${unit}`;const pad={l:70,r:70,t:52,b:62},w=width-pad.l-pad.r,h=height-pad.t-pad.b;
  const flat=kind==="time"?analysis.timeSeries.flatMap(s=>s.values.map(v=>v.value)):kind==="plots"?(session?.comparePlots||[]).map(x=>x.value):(session?.compareTreatments||[]).map(x=>x.average||0);const max=Math.max(1,...flat);const grid=[0,.25,.5,.75,1].map(f=>{const y=pad.t+h-h*f;return `<line x1="${pad.l}" y1="${y}" x2="${pad.l+w}" y2="${y}" stroke="#d8e3e1"/><text x="${pad.l-8}" y="${y+4}" text-anchor="end" font-size="11" fill="#526b67">${(max*f).toFixed(max<10?1:0)}</text>`}).join("");let marks="";
  if(kind==="time"){const count=analysis.sessions.length;marks=analysis.timeSeries.map((series,si)=>{const points=analysis.sessions.map((s,i)=>{const found=series.values.find(v=>v.sessionId===s.id);return found?`${pad.l+(count===1?w/2:i*w/(count-1))},${pad.t+h-found.value/max*h}`:null}).filter(Boolean).join(" ");return `<polyline points="${points}" fill="none" stroke="${colors[si%colors.length]}" stroke-width="3"/>`+analysis.sessions.map((s,i)=>{const found=series.values.find(v=>v.sessionId===s.id);if(!found)return"";const cx=pad.l+(count===1?w/2:i*w/(count-1)),cy=pad.t+h-found.value/max*h;return `<circle cx="${cx}" cy="${cy}" r="4" fill="${colors[si%colors.length]}"/>`}).join("")+`<text x="${pad.l+w-5}" y="${pad.t+15+si*14}" text-anchor="end" font-size="10" fill="${colors[si%colors.length]}">${esc(series.plot)}</text>`}).join("")+analysis.sessions.map((s,i)=>`<text x="${pad.l+(count===1?w/2:i*w/(count-1))}" y="${pad.t+h+22}" text-anchor="middle" font-size="9" fill="#526b67">${esc(s.label)}</text>`).join("")}else{const source=kind==="plots"?(session?.comparePlots||[]).map(x=>({label:x.plot,value:x.value})):(session?.compareTreatments||[]).map(x=>({label:x.treatment,value:x.average||0}));const bw=Math.max(12,w/Math.max(1,source.length)-10);marks=source.map((x,i)=>{const xp=pad.l+i*w/source.length+(w/source.length-bw)/2,bh=x.value/max*h;return `<rect x="${xp}" y="${pad.t+h-bh}" width="${bw}" height="${bh}" rx="4" fill="#52cbb8"/><text x="${xp+bw/2}" y="${pad.t+h+22}" text-anchor="middle" font-size="10" fill="#526b67">${esc(x.label)}</text>`}).join("")}
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="#fff"/><text x="${pad.l}" y="28" font-family="Arial" font-size="17" font-weight="700" fill="#173b36">${esc(title)}</text><g font-family="Arial">${grid}<line x1="${pad.l}" y1="${pad.t+h}" x2="${pad.l+w}" y2="${pad.t+h}" stroke="#69807c"/>${marks}</g></svg>`;
}

export function comparisonChartSvg(comparison:ComparisonResult,width=720,height=360){const pad={l:70,r:45,t:55,b:70},w=width-pad.l-pad.r,h=height-pad.t-pad.b;const vals=comparison.points.flatMap(p=>Object.values(p.values).filter((v):v is number=>v!=null));const max=Math.max(1,...vals);const grid=[0,.25,.5,.75,1].map(f=>{const y=pad.t+h-h*f;return`<line x1="${pad.l}" y1="${y}" x2="${pad.l+w}" y2="${y}" stroke="#d8e3e1"/><text x="${pad.l-8}" y="${y+4}" text-anchor="end" font-size="10" fill="#526b67">${(max*f).toFixed(max<10?1:0)}</text>`}).join("");let marks="";if(comparison.chartType==="line"){marks=comparison.points.map((point,pi)=>{const points=comparison.series.map((s,i)=>{const v=point.values[s.key];return v==null?null:`${pad.l+(comparison.series.length===1?w/2:i*w/(comparison.series.length-1))},${pad.t+h-v/max*h}`}).filter(Boolean).join(" ");return`<polyline points="${points}" fill="none" stroke="${colors[pi%colors.length]}" stroke-width="3"/>`}).join("")+comparison.series.map((s,i)=>`<text x="${pad.l+(comparison.series.length===1?w/2:i*w/(comparison.series.length-1))}" y="${pad.t+h+22}" text-anchor="middle" font-size="9" fill="#526b67">${esc(s.label)}</text>`).join("")+comparison.points.map((p,i)=>`<text x="${pad.l+w-4}" y="${pad.t+14+i*13}" text-anchor="end" font-size="9" fill="${colors[i%colors.length]}">${esc(p.category)}</text>`).join("")}else{const groupW=w/Math.max(1,comparison.points.length),barW=Math.max(8,(groupW-12)/Math.max(1,comparison.series.length));marks=comparison.points.map((p,pi)=>comparison.series.map((s,si)=>{const v=p.values[s.key];if(v==null)return"";const x=pad.l+pi*groupW+6+si*barW,bh=v/max*h;return`<rect x="${x}" y="${pad.t+h-bh}" width="${barW-2}" height="${bh}" rx="3" fill="${colors[si%colors.length]}"/>`}).join("")+`<text x="${pad.l+pi*groupW+groupW/2}" y="${pad.t+h+22}" text-anchor="middle" font-size="9" fill="#526b67">${esc(p.category)}</text>`).join("")+comparison.series.map((s,i)=>`<rect x="${pad.l+i*130}" y="${height-24}" width="10" height="10" fill="${colors[i%colors.length]}"/><text x="${pad.l+14+i*130}" y="${height-15}" font-size="9" fill="#526b67">${esc(s.label)}</text>`).join("")}return`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="#fff"/><text x="${pad.l}" y="26" font-family="Arial" font-size="15" font-weight="700" fill="#173b36">${esc(comparison.title)}</text><g font-family="Arial">${grid}<line x1="${pad.l}" y1="${pad.t+h}" x2="${pad.l+w}" y2="${pad.t+h}" stroke="#69807c"/>${marks}</g></svg>`}
