import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import { ProjectObservationSnapshot } from "./observationAnalysis";
import { ComparisonResult } from "./observationComparison";
import { sortLayout } from "./observationSort";

export const safeFilename=(name:string)=>name.normalize("NFKD").replace(/[^a-zA-Z0-9_-]+/g,"-").replace(/^-+|-+$/g,"").toLowerCase()||"project";
const headerFill="1F6F63",accentFill="DDF4EF";
const styleHeader=(row:ExcelJS.Row)=>{row.font={bold:true,color:{argb:"FFFFFFFF"}};row.fill={type:"pattern",pattern:"solid",fgColor:{argb:`FF${headerFill}`}};row.alignment={vertical:"middle"};row.height=24};
const sheetName=(name:string,used:Set<string>)=>{let base=name.replace(/[\\/?*:[\]]/g," ").trim().slice(0,31)||"Observation",next=base,i=2;while(used.has(next))next=`${base.slice(0,27)} ${i++}`;used.add(next);return next};
export async function createObservationWorkbook(snapshot:ProjectObservationSnapshot,comparison?:ComparisonResult|null){
  const wb=new ExcelJS.Workbook();wb.creator="ResearchPal";wb.created=new Date();const raw=wb.addWorksheet("Raw Data",{views:[{state:"frozen",ySplit:1}]});raw.columns=[{header:"Date",key:"date",width:14},{header:"Time",key:"time",width:11},{header:"Round",key:"round",width:9},{header:"Session ID",key:"sessionId",width:26},{header:"Plot ID",key:"plotId",width:26},{header:"Plot Name",key:"plot",width:18},{header:"Treatment ID",key:"treatmentId",width:14},{header:"Treatment Name",key:"treatment",width:16},{header:"Replication ID",key:"replicationId",width:14},{header:"Replication Name",key:"replication",width:16},{header:"Observation",key:"observation",width:26},{header:"Value",key:"value",width:14},{header:"Unit",key:"unit",width:12},{header:"Note",key:"note",width:36}];snapshot.rawRows.forEach(x=>raw.addRow([x.date,x.date,x.round,x.measurementSessionId,x.plotId,x.plot,x.treatmentId,x.treatment,x.replicationId,x.replication,x.observation,x.value as any,x.unit||null,x.note||null]));raw.getColumn("date").numFmt="yyyy-mm-dd";raw.getColumn("time").numFmt="hh:mm:ss";raw.autoFilter={from:"A1",to:"N1"};styleHeader(raw.getRow(1));raw.getColumn("note").alignment={wrapText:true,vertical:"top"};
  const summary=wb.addWorksheet("Summary",{views:[{state:"frozen",ySplit:1}]});summary.columns=[{header:"Observation",key:"observation",width:26},{header:"Unit",key:"unit",width:12},{header:"Treatment",key:"treatment",width:14},{header:"Count",key:"count",width:12},{header:"Average",key:"average",width:14},{header:"Minimum",key:"minimum",width:14},{header:"Maximum",key:"maximum",width:14}];snapshot.analyses.forEach(a=>{summary.addRow({observation:a.type.name,unit:a.type.unit||"",treatment:"All",...a.summary});a.summary.byTreatment.forEach(t=>summary.addRow({observation:a.type.name,unit:a.type.unit||"",...t}))});styleHeader(summary.getRow(1));summary.getColumn("average").numFmt="0.00";summary.getColumn("minimum").numFmt="0.00";summary.getColumn("maximum").numFmt="0.00";
  const used=new Set(["Raw Data","Summary"]);for(const analysis of snapshot.analyses){const sheet=wb.addWorksheet(sheetName(analysis.type.name,used),{views:[{state:"frozen",ySplit:2,xSplit:3}]});const rows=new Map<string,any>();snapshot.rawRows.filter(x=>x.observationTypeId===analysis.type._id.toString()).forEach(x=>{const row=rows.get(x.plotId)||{Plot:x.plot,Treatment:x.treatment,Replication:x.replication,treatmentId:x.treatmentId,replicationId:x.replicationId,plotId:x.plotId};row[x.measurementSessionId]=Number(x.value);rows.set(x.plotId,row)});sheet.addRow([analysis.type.name,null,null,`Unit: ${analysis.type.unit||"none"}`]);sheet.addRow(["Treatment","Replication","Plot",...analysis.sessions.map(s=>s.label)]);sortLayout([...rows.values()],"treatment").forEach(row=>sheet.addRow([row.Treatment,row.Replication,row.Plot,...analysis.sessions.map(s=>row[s.id]??null)]));sheet.mergeCells("A1:C1");sheet.getRow(1).font={bold:true,size:16,color:{argb:`FF${headerFill}`}};styleHeader(sheet.getRow(2));sheet.columns.forEach((col,i)=>col.width=i===0?18:i>2?22:14);analysis.sessions.forEach((_,i)=>sheet.getColumn(i+4).numFmt="0.00")}
  return Buffer.from(await wb.xlsx.writeBuffer());
}
const addPdfTableHeader=(doc:PDFKit.PDFDocument,y:number,cols:string[])=>{doc.rect(42,y,doc.page.width-84,22).fill("#1f6f63");doc.fillColor("white").font("Helvetica-Bold").fontSize(8);const widths=[65,65,58,58,72,45,45,120];let x=46;cols.forEach((c,i)=>{doc.text(c,x,y+7,{width:widths[i]});x+=widths[i]});doc.fillColor("#173b36");return widths};
export async function createObservationPdf(snapshot:ProjectObservationSnapshot,comparison?:ComparisonResult|null){return new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:"A4",margin:42,bufferPages:true});const chunks:Buffer[]=[];doc.on("data",c=>chunks.push(c));doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);const title=String(snapshot.project.title||"Project");doc.fillColor("#173b36").font("Helvetica-Bold").fontSize(24).text("Project Observation Report");doc.moveDown(.3).font("Helvetica").fontSize(12).text(title);doc.moveDown();doc.fillColor("#526b67").fontSize(9).text(`Report date: ${new Date().toISOString().slice(0,10)}`);doc.text(`Plots: ${snapshot.plots.length}   Treatments: ${snapshot.project.treatmentsCount??""}   Replications: ${snapshot.project.replicationsCount??""}`);doc.moveDown(1.5);doc.fillColor("#173b36").font("Helvetica-Bold").fontSize(16).text("Observation Summary");snapshot.types.forEach((type:any)=>{const a=snapshot.analyses.find(x=>x.type._id.toString()===type._id.toString());const count=snapshot.rawRows.filter(x=>x.observationTypeId===type._id.toString()).length;doc.moveDown(.5).fontSize(11).text(`${type.name}${type.unit?` (${type.unit})`:""}`);doc.font("Helvetica").fontSize(9).fillColor("#526b67").text(a?`Samples: ${a.summary.count}   Average: ${a.summary.average?.toFixed(2)??"-"}   Min: ${a.summary.minimum??"-"}   Max: ${a.summary.maximum??"-"}`:`Samples: ${count}`)});
  doc.addPage();doc.fillColor("#173b36").font("Helvetica-Bold").fontSize(18).text("Measurement Data");doc.moveDown();const cols=["Date","Plot","Treat.","Rep.","Observation","Value","Unit","Note"];let y=doc.y;const widths=addPdfTableHeader(doc,y,cols);y+=24;for(const row of snapshot.rawRows){if(y>750){doc.addPage();y=42;addPdfTableHeader(doc,y,cols);y+=24}const values=[row.date.toISOString().slice(0,10),row.plot,row.treatment,row.replication,row.observation,String(row.value),row.unit,row.note];let x=46;doc.font("Helvetica").fontSize(7).fillColor("#173b36");values.forEach((v,i)=>{doc.text(v,x,y+3,{width:widths[i]-4,height:26,ellipsis:true});x+=widths[i]});doc.moveTo(42,y+28).lineTo(doc.page.width-42,y+28).strokeColor("#d8e3e1").stroke();y+=29}const pages=doc.bufferedPageRange();for(let i=0;i<pages.count;i++){doc.switchToPage(i);doc.page.margins.bottom=0;doc.fontSize(8).fillColor("#718681").text(`ResearchPal - ${title}`,42,doc.page.height-28,{width:300,lineBreak:false});doc.text(`Page ${i+1} of ${pages.count}`,doc.page.width-130,doc.page.height-28,{width:88,align:"right",lineBreak:false})}doc.end()})}
