import { Router } from "express";
import { validate } from "../../MiddleWare/Validator";
import * as c from "../../contoller/Observations";
import * as s from "../../Schema/Observations";
import { asyncHandler } from "../../utils/asyncHandler";

const router = Router();
router.post("/types", validate(s.CreateObservationTypeSchema), asyncHandler(c.CreateObservationType));
router.get("/types", validate(s.ObservationTypeQuerySchema), asyncHandler(c.ListObservationTypes));
router.patch("/types", validate(s.UpdateObservationTypeSchema), asyncHandler(c.UpdateObservationType));
router.delete("/types", validate(s.DeleteObservationTypeSchema), asyncHandler(c.DeleteObservationType));
router.post("/records", validate(s.CreateObservationRecordSchema), asyncHandler(c.CreateObservationRecord));
router.post("/records/bulk", validate(s.BulkObservationRecordsSchema), asyncHandler(c.BulkCreateObservationRecords));
router.get("/records", validate(s.ObservationRecordsQuerySchema), asyncHandler(c.ListObservationRecords));
router.patch("/records", validate(s.UpdateObservationRecordSchema), asyncHandler(c.UpdateObservationRecord));
router.delete("/records", validate(s.DeleteObservationRecordSchema), asyncHandler(c.DeleteObservationRecord));
router.get("/summary", validate(s.ObservationAnalyticsQuerySchema), asyncHandler(c.GetObservationSummary));
router.get("/graphs", validate(s.ObservationAnalyticsQuerySchema), asyncHandler(c.GetObservationGraphs));
router.post("/compare", validate(s.ObservationComparisonSchema), asyncHandler(c.CompareObservationData));
router.get("/export", validate(s.ObservationExportQuerySchema), asyncHandler(c.ExportObservations));
router.post("/export/charts",validate(s.ChartExportSchema),asyncHandler(c.ExportCharts));
export default router;
